repos:
  - repo: https://github.com/mwouts/jupytext
    rev: v1.13.7  # CURRENT_TAG/COMMIT_HASH
    hooks:
      - id: jupytext
        args: [ --from, ipynb, --to, "py:percent", --pipe, black ]
        additional_dependencies:
          - black==20.8b1 # Matches hook
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
        args: [ '--maxkb=10000' ]
      - id: trailing-whitespace
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: end-of-file-fixer

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: ADHOCS

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: ADHOCS
        args: [ --max-line-length=131 ]

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.0.3
    hooks:
      - id: sqlfluff-fix
        types: [ sql ]
        args: [ --dialect=bigquery, --rules=LT02 ]